import { initializeApp, getApps } from 'firebase/app';
import { 
  getFirestore, 
  collection, 
  addDoc, 
  serverTimestamp, 
  doc, 
  increment, 
  updateDoc, 
  getDoc,
  setDoc,
  query,
  orderBy,
  limit,
  getDocs
} from 'firebase/firestore';

// In a real AI Studio app, this is auto-generated by the set_up_firebase tool
let db: any = null;

async function initFirebase() {
  try {
    // @ts-ignore - this file might not exist yet if set_up_firebase failed
    const config = await import(/* @vite-ignore */ '../../firebase-applet-config.json').then(m => m.default).catch(() => null);
    
    if (config && config.apiKey && getApps().length === 0) {
      const app = initializeApp(config);
      db = getFirestore(app);
    } else if (getApps().length > 0) {
      db = getFirestore(getApps()[0]);
    }
  } catch (e) {
    console.warn("Firebase config not found or invalid. Analytics and cloud saving disabled.");
  }
}

// Initialize on load
initFirebase();

export { db };

export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null) {
  const errInfo = {
    error: error instanceof Error ? error.message : String(error),
    operationType,
    path
  };
  console.error('Firestore Error: ', JSON.stringify(errInfo));
  // We don't want to crash the whole app if user tracking fails
}

export async function trackCalculation() {
  if (!db) return;
  try {
    const statsRef = doc(db, 'metadata', 'global_stats');
    const statsDoc = await getDoc(statsRef);
    
    if (!statsDoc.exists()) {
      await setDoc(statsRef, { totalCalculations: 1 });
    } else {
      await updateDoc(statsRef, {
        totalCalculations: increment(1)
      });
    }
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, 'metadata/global_stats');
  }
}

export async function submitResult(data: any) {
  if (!db) return;
  try {
    await addDoc(collection(db, 'submissions'), {
      ...data,
      timestamp: serverTimestamp()
    });
    // Also track as a generic usage
    await trackCalculation();
  } catch (error) {
    handleFirestoreError(error, OperationType.CREATE, 'submissions');
  }
}

export async function getDashboardStats() {
  if (!db) return null;
  try {
    const statsRef = doc(db, 'metadata', 'global_stats');
    const statsDoc = await getDoc(statsRef);
    
    const submissionsQuery = query(collection(db, 'submissions'), orderBy('timestamp', 'desc'), limit(50));
    const submissionsSnap = await getDocs(submissionsQuery);
    
    const submissions = submissionsSnap.docs.map(d => ({
      id: d.id,
      ...d.data()
    }));

    return {
      total: statsDoc.exists() ? statsDoc.data().totalCalculations : 0,
      recent: submissions
    };
  } catch (error) {
    handleFirestoreError(error, OperationType.GET, 'dashboard');
    return null;
  }
}
